let profileInfo = {
    "login":"null",
    "id":"null",
    "node_id":"null",
    "avatar_url":"null",
    "gravatar_id":"null",
    "url":"null",
    "html_url":"link",
    "followers_url":"link",
    "following_url":"link",
    "gists_url":"link",
    "starred_url":"null",
    "subscriptions_url":"link",
    "organizations_url":"link",
    "repos_url":"link",
    "events_url":"null",
    "received_events_url":"null",
    "type":"null",
    "site_admin":"null",
    "name":"input",
    "company":"input",
    "blog":"input",
    "location":"input", 
    "email":"input",
    "hireable":"input",
    "bio":"input",
    "twitter_username":"input",
    "public_repos":"label",
    "public_gists":"label",
    "followers":"label",
    "following":"label",
    "created_at":"null",
    "updated_at":"null",
    "plan":"null"
}

export {profileInfo};