FROM python:3.8.3

EXPOSE 8000
ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT pytest --cov

